// <auto-generated />
using AnimeCD.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeCD.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240922170428_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeCD.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Sci-fi"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Mecha"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "School"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "Shounen"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Name = "Shoujo"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 20,
                            Name = "Harem"
                        });
                });

            modelBuilder.Entity("AnimeCD.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ochikoshi Tomonori",
                            Description = "Câu chuyện về một cô thiếu nữ tên Lucy Heartfilia, khao khát của cô là gia nhập Hội Pháp sư nổi tiếng Fairy Tail. Trên đường phiêu lưu, Lucy đã vô tình gặp gỡ Natsu Salamander Dragneel, một thành viên của Fairy Tail, người sở hữu pháp thuật cổ đại Sát Long. Thế rồi Lucy được Natsu giới thiệu vào Hội Pháp sư Fairy Tail và cùng anh chàng này tham gia vô số nhiệm vụ khó khăn nhưng cũng không kém phần thú vị. ",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Serial = "SWD9999001",
                            Title = "Fairy Tail"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Uda Kounosuke",
                            Description = "Monkey D. Luffy, 1 cậu bé rất thích Đảo hải tặc có ước mơ tìm được kho báu One Piece và trở thành Vua hải tặc - Pirate King. Lúc nhỏ, Luffy tình cờ ăn phải trái quỉ (Devil Fruit) Gomu Gomu, nó cho cơ thể cậu khả năng co dãn đàn hồi như cao su nhưng đổi lại cậu sẽ không bao giờ biết bơi. Hãy cùng theo dõi xem liệu Luffy có thể trở thành đạt được kho báu One Piece và trở thành Vua Hải Tặc không nhé.",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Serial = "CAW777777701",
                            Title = "One Piece"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Julian Button",
                            Description = "Fable là một tay sát thủ lão luyện giỏi nhất trong lĩnh vực của mình. Tuy nhiên, anh ta đã giết rất nhiều người đến nỗi ông chủ của anh ta yêu cầu anh ta phải nằm im trong một thời gian. ",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Serial = "RITO5555501",
                            Title = "The Fable"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Abby Muscles",
                            Description = "Kỷ nguyên của các cuộc đại chiến nảy lửa giữa 5 chủng tộc để giành quyền bá chủ mặt đất đã kết thúc với phần thắng thuộc về nhân loại do Anh Hùng Sid lãnh đạo. Tuy nhiên, thế giới đó bất ngờ bị ”thay đổi” trước sự chứng kiến của chàng trai tên Kai. Trong thế giới đó, Kai đã thấy Anh Hùng Sid không còn tồn tại, dẫn đến sự thất bại của con người trong trận đại chiến giữa 5 chủng tộc.",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Serial = "WS3333333301",
                            Title = "Naze Boku no Sekai wo Daremo Oboeteinai no ka?"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Ron Parker",
                            Description = "The New Gate là một game online thu hút hàng nghìn người chơi tham gia. Khi trò game trở thành một nơi chết chóc, nhờ vào Shin, một trong người chơi mạnh nhất đá đánh bại chùm cuối và giải thoát mọi người. Nhưng sau khi chiến thắng, Shin bị một tia sáng chiếu vào và kéo anh ta tới thế giới game đó 500 năm sau và bị mắc kẹt luôn trong đó. ",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Serial = "SOTJ1111111101",
                            Title = "The New Gate"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Laura Phantom",
                            Description = "Phim dựa trên 6 câu chuyện: Lọ Lem, Cô Bé Quàng Khăn Đỏ, Hansel và Gretel, Người Thợ Giày và Lũ Yêu Tinh, Những Nhạc Sĩ Thành Bremen, Người Thổi Sáo Thành Hamelin.",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Serial = "FOT000000001",
                            Title = "Grimm Kumikyoku"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
